baseURL = 'https://HaoZhong03.github.io'
languageCode = 'zh-cn'
title = 'HaoZhong03 blog'
theme = 'PaperMod'

cleanDestinationDir = true
enableEmoji = true              # å…è®¸ä½¿ç”¨Emojiè¡¨æƒ…
enableInlineShortcodes = true   # å…è®¸å†…è”çŸ­ç 
enableRobotsTXT = true          # å…è®¸çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“
hasCJKLanguage = true           # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å«ä¸­æ–‡æ—¥æ–‡éŸ©æ–‡
pagination.pagerSize = 15       # æ¯é¡µæ–‡ç« æ•°é‡

# è¯­è¨€è®¾ç½®
defaultContentLanguage = "zh"

# å•è¯­è¨€ï¼Œå¿…é¡»åœ¨æ­¤å¤„ï¼Œä»¥ä¸‹è®¾ç½®ä¹‹å‰
[languages]
[languages.zh]
    languageName = "ä¸­æ–‡"

[markup.goldmark.renderer]
    unsafe = true               # htmlæ ‡ç­¾
[markup.highlight]
    codeFences = true           # ä»£ç æ¡†
    guessSyntax = false
    lineNos = false
    lineNumbersInTable = false  # tableåˆ†éš”è¡Œå·ä¸ä»£ç 
    noClasses = true            # ä»£ç å—styleè€Œéclass
    style = "monokai"           # é…è‰²æ–¹æ¡ˆ

# èœå•è®¾ç½®
[[menu.main]]
  identifier = "archives"
  name = "âŒ›ä¸–ç•Œçº¿"
  url = "/archives/"
  weight = 1
[[menu.main]]
  identifier = "docs"
  name = "ğŸ“•æ–‡æ¡£"
  url = "/docs/"
  weight = 2
[[menu.main]]
  identifier = "tags"
  name = "ğŸ“Œæ ‡ç­¾"
  url = "/tags/"
  weight = 3
[[menu.main]]
  identifier = "categolories"
  name = "ğŸ“åˆ†ç±»"
  url = "/categories/"
  weight = 4
[[menu.main]]
  identifier = "search"
  name = "ğŸ”æœç´¢"
  url = "/search"
  weight = 5
[[menu.main]]
  identifier = "about"
  name = "ğŸå…³äº"
  url = "/about/"
  weight = 6

[[permalinks]]
    post = "/post/:section/:slug/"  # é“¾æ¥æ ¼å¼

# æœç´¢åŠŸèƒ½
[outputs]
  home = ["HTML", "RSS", "JSON"]

# ä¸»é¢˜è®¾ç½®
[params]
    math = true
    env = "production"
    description = "è¿™æ˜¯ä¸€æ®µæè¿°"
    author = "HaoZhong03"
    keywords = ["blog"]
    DateFormat = "2006-01-02"
    ShowCodeCopyButtons = true  # ä»£ç å¤åˆ¶æŒ‰é’®
    ShowFullTextinRSS = true    # RSSå±•ç¤ºå…¨æ–‡
    defaultTheme = "auto"       # é»˜è®¤ä¸»é¢˜é¢œè‰²
    hideSummary = false         # éšè—æ‘˜è¦
    showtoc = true              # æ˜¾ç¤ºç›®å½•
    tocopen = true              # ç›®å½•é»˜è®¤å±•å¼€
    ShowPostNavLinks = true     # æ˜¾ç¤ºä¸Šä¸€ç¯‡/ä¸‹ä¸€ç¯‡
    ShowBreadCrumbs = true      # æ–‡ç« é¡¶éƒ¨é¢åŒ…å±‘å¯¼èˆª
    # ShowRssButtonInSectionTermList = true
    comments = true             # å±•ç¤ºè¯„è®º
    hideFooter = false          # éšè—é¡µè„šä¿¡æ¯
    # ShowAllPagesInArchive = true #

# å·¦ä¸Šè§’æ ‡ç­¾
[params.label]
    text = "Home"
    # icon = "images/favicon-32x32-.png"
    # iconHeight = 36

[params.assets]
    favicon = "images/favicon-16x16-.png"        # æµè§ˆå™¨æ ‡ç­¾å›¾æ ‡
    favicon16x16 = "images/favicon-16x16-.png"   # æµè§ˆå™¨æ ‡ç­¾å›¾æ ‡
    favicon32x32 = "images/favicon-32x32-.png"   # æµè§ˆå™¨æ ‡ç­¾å›¾æ ‡
    disableHLJS = true  # ä¸ä½¿ç”¨highlight.js

[params.profileMode]
    enabled = true  # ä¸ªäººä¸»é¡µæ¨¡å¼
    title = "HaoZhong03"
    subtitle = "El Psy Kongroo"
    imageUrl = "https://s21.ax1x.com/2025/09/16/pVfHj39.jpg"
    imageWidth = ""
    imageHeight = ""

# ä¸»é¡µæŒ‰é’®
[[params.profileMode.buttons]]
    name = "ğŸ‘‰ç‚¹å‡»æŸ¥çœ‹ä¸–ç•Œçº¿ğŸ‘ˆ"
    url = "/archives"

# ç¤¾äº¤å›¾æ ‡
[[params.socialIcons]]
  name = "bilibili"
  url = "https://space.bilibili.com/8917343"
[[params.socialIcons]]
  name = "neteaseCloudMusic"
  url = "https://music.163.com/song?id=2670691867&uct2=U2FsdGVkX1/so8I9i5GJuC+OVcTqKP4mZ/l51gOpX5M="
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/HaoZhong03"

# fuse.jsæ¨¡ç³Šæœç´¢
[params.fuseOpts]
  isCaseSensitive = false   # ä¸åŒºåˆ†å¤§å°å†™
  shouldSort = true         # æœç´¢ç»“æœæ’åº
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

[params.page.comment]
  enable = true
  # giscus comment è¯„è®ºç³»ç»Ÿè®¾ç½® (https://giscus.app/zh-CN)
[params.page.comment.giscus]
  # ä½ å¯ä»¥å‚è€ƒå®˜æ–¹æ–‡æ¡£æ¥ä½¿ç”¨ä¸‹åˆ—é…ç½®
  enable = true
  repo = "Haozhong03/Haozhong03.github.io"
  repoId = "R_kgDOPutG0g"
  category = "Announcements"
  categoryId = "DIC_kwDOPutG0s4Cvi80"
        # ä¸ºç©ºæ—¶è‡ªåŠ¨é€‚é…å½“å‰ä¸»é¢˜ i18n é…ç½®
  lang = "zh-CN"
  mapping = "pathname"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  lazyLoading = false
  lightTheme = "light"
  darkTheme = "dark"
  discussionTitle = "è¯´ç‚¹ä»€ä¹ˆ" # æŒ‰éœ€å¡«å†™ï¼Œè¯„è®ºæ¡†ä¸Šæ–¹çš„æ ‡é¢˜

# åˆ†ç±»ç­‰çº§
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# è¯„è®º
[params.twikoo]
  version = "1.6.16"

# è®¿å®¢ç»Ÿè®¡
[params.busuanzi]
  enable = true

